{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nbg.fullname" . }}
  labels: {{- include "nbg.labels" (dict "root" . "component" "ingress") | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls: {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.uiHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: {service: {name: {{ include "nbg.name" (dict "root" . "component" "ui") }}, port: {name: http}}}
    - host: {{ .Values.ingress.netboxHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: {service: {name: {{ include "nbg.name" (dict "root" . "component" "netbox") }}, port: {name: http}}}
{{- end }}
